sudo: false
language: cpp
addons:
  apt:
    packages:
      - curl
compiler:
  - clang
before_install:
  - curl https://cmake.org/files/v3.4/cmake-3.4.0-Linux-x86_64.tar.gz -o cmake-3.4.0-Linux-x86_64.tar.gz
  - tar xf cmake-3.4.0-Linux-x86_64.tar.gz
  - export PATH=$PWD/cmake-3.4.0-Linux-x86_64/bin/:$PATH
script:
  - travis/build.sh
